# Generated by Django 3.1.4 on 2021-04-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlist',
            options={'verbose_name': 'Product List Page'},
        ),
    ]
