# Generated by Django 3.1.4 on 2021-04-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_product_funfun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='funfun',
        ),
    ]
