# Generated by Django 3.1.4 on 2021-04-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('cart', '0012_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
